os: Visual Studio 2017
version: '2.5.6.{build}'
skip_tags: true
install:
- ps: |
    $full_build = Test-Path env:GHFVS_KEY
    git submodule init
    git submodule sync

    if ($full_build) {
      $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
      $fileContent += $env:GHFVS_KEY.Replace(' ', "`n")
      $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
      Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
    } else {
      git submodule deinit script
    }

    git submodule update --recursive --force
    nuget restore GitHubVS.sln
build_script:
- ps: scripts\build.ps1 -AppVeyor -BuildNumber:$env:APPVEYOR_BUILD_NUMBER
test:
  categories:
    except:
      - Timings
after_test:
- ps: |  
    choco install opencover.portable codecov
    OpenCover.Console.exe -register:user -target:"nunit3-console.exe" "-targetargs: visualstudio\test\GitHub.Api.UnitTests\bin\Release\GitHub.Api.UnitTests.dll visualstudio\test\GitHub.App.UnitTests\bin\Release\GitHub.App.UnitTests.dll visualstudio\test\GitHub.Exports.Reactive.UnitTests\bin\Release\GitHub.Exports.Reactive.UnitTests.dll visualstudio\test\GitHub.Exports.UnitTests\bin\Release\GitHub.Exports.UnitTests.dll visualstudio\test\GitHub.Extensions.UnitTests\bin\Release\GitHub.Extensions.UnitTests.dll visualstudio\test\GitHub.InlineReviews.UnitTests\bin\Release\GitHub.InlineReviews.UnitTests.dll visualstudio\test\GitHub.Primitives.UnitTests\bin\Release\GitHub.Primitives.UnitTests.dll visualstudio\test\GitHub.TeamFoundation.UnitTests\bin\Release\GitHub.TeamFoundation.UnitTests.dll visualstudio\test\GitHub.UI.UnitTests\bin\Release\GitHub.UI.UnitTests.dll visualstudio\test\GitHub.VisualStudio.UnitTests\bin\Release\GitHub.VisualStudio.UnitTests.dll visualstudio\test\MetricsTests\MetricsTests\bin\Release\MetricsTests.dll visualstudio\test\TrackingCollectionTests\bin\Release\TrackingCollectionTests.dll --where cat != Timings" -output:".\coverage.xml"
    codecov -f "coverage.xml"
on_success:
- ps: |
    if ($full_build) {
      script\Sign-Package -AppVeyor
    }
