version: '{build}'
install:
- ps: >-
    $full_build = Test-Path env:GHFVS_KEY

    git submodule init
    
    git submodule sync

    if ($full_build) {
      $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n"
      $fileContent += $env:GHFVS_KEY.Replace(' ', "`n")
      $fileContent += "`n-----END RSA PRIVATE KEY-----`n"
      Set-Content c:\users\appveyor\.ssh\id_rsa $fileContent
    } else {
      git submodule deinit script
    }

    git submodule update --recursive --force

    nuget restore GitHubVS.sln
build_script:
- ps: scripts\build.ps1
test_script:
- ps: >-
    scripts\Run-Tests.ps1 -AppVeyor
